import { ApiProvider } from "@reduxjs/toolkit/dist/query/react";
import "./globals.css";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { apiSlice } from "@/api/apiSlice";
import ApiProviderClient from "@/components/providers/ApiProviderClient";

const nunito = Nunito({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <ApiProviderClient>{children}</ApiProviderClient>
      </body>
    </html>
  );
}
